import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        "silk-gold": { DEFAULT: "hsl(var(--silk-gold))", light: "hsl(var(--silk-gold-light))", dim: "hsl(var(--silk-gold-dim))" },
        champagne: "hsl(var(--champagne))",
        obsidian: "hsl(var(--obsidian))",
        graphite: "hsl(var(--graphite))",
        stone: "hsl(var(--stone))",
        mist: "hsl(var(--mist))",
        ivory: { DEFAULT: "hsl(var(--ivory))", warm: "hsl(var(--ivory-warm))" },
        "deep-slate": { DEFAULT: "hsl(40 25% 94%)", light: "hsl(0 0% 60%)" },
        charcoal: { DEFAULT: "hsl(0 0% 8%)", light: "hsl(0 0% 16%)", dark: "hsl(0 0% 3%)" },
        beige: { DEFAULT: "hsl(0 0% 14%)", light: "hsl(0 0% 11%)" },
        limestone: { DEFAULT: "hsl(0 0% 4%)", warm: "hsl(0 0% 6%)" },
        "cool-grey": "hsl(0 0% 9%)",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))", foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))", "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))", "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))", ring: "hsl(var(--sidebar-ring))",
        },
      },
      fontFamily: {
        serif: ["Playfair Display", "Georgia", "serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
        arabic: ["Noto Sans Arabic", "Tahoma", "sans-serif"],
      },
      fontSize: {
        display: ["clamp(3rem, 8vw, 7rem)", { lineHeight: "1.0", letterSpacing: "-0.03em", fontWeight: "400" }],
        headline: ["clamp(2rem, 4.5vw, 4rem)", { lineHeight: "1.1", letterSpacing: "-0.025em", fontWeight: "400" }],
        title: ["clamp(1.4rem, 2.8vw, 2.5rem)", { lineHeight: "1.2", letterSpacing: "-0.015em", fontWeight: "400" }],
        "body-lg": ["1.125rem", { lineHeight: "1.8", fontWeight: "300" }],
      },
      borderRadius: {
        lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)",
        pill: "9999px", sharp: "0px", glass: "24px", "glass-sm": "16px", "glass-lg": "32px",
      },
      spacing: { section: "10rem", "section-md": "7rem", "section-sm": "5rem", luxury: "12rem" },
      transitionTimingFunction: {
        expo: "cubic-bezier(0.16, 1, 0.3, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        smooth: "cubic-bezier(0.45, 0, 0.55, 1)",
        "out-expo": "cubic-bezier(0.16, 1, 0.3, 1)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { "0%": { opacity: "0", transform: "translateY(12px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "scale-in": { "0%": { transform: "scale(0.95)", opacity: "0" }, "100%": { transform: "scale(1)", opacity: "1" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.6s cubic-bezier(0.16, 1, 0.3, 1)",
        "scale-in": "scale-in 0.4s cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
